## Notebook in process

In [1]:
from __future__ import print_function
__author__ = 'mo'
import pylab as pl
import numpy as np
%pylab inline

import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd
import geopandas as gp
import json

import statsmodels.formula.api as smf
from statsmodels.graphics.api import abline_plot 
from pandas.stats.plm import PanelOLS

import sklearn.cluster
from sklearn import mixture
from PIL import Image
from scipy.misc import imread
from scipy.cluster.vq import kmeans2
#import mplleaflet
#import shapely.geometry as geom
import networkx as nx
import xlrd

Populating the interactive namespace from numpy and matplotlib

In [14]:
panel = pd.read_csv('/Users/mariaortiz/Desktop/expansion_urbana_mx/paneltest.csv')
panel

    year                            city  id         pop     area
0   1980          ZM del Valle de M�xico   1  14,122,991   51,908
1   2000          ZM del Valle de M�xico   1  18,396,677  167,081
2   2005          ZM del Valle de M�xico   1  19,239,910  174,616
3   2010          ZM del Valle de M�xico   1  20,116,842  185,291
4   1980               ZM de Guadalajara   2   2,244,715   12,726
5   2000               ZM de Guadalajara   2   3,699,136   39,795
6   2005               ZM de Guadalajara   2   4,095,853   43,045
7   2010               ZM de Guadalajara   2   4,434,878   48,585
8   1980               ZM de Minatitl�n    3   2,061,744   12,855
9   2000               ZM de Minatitl�n    3   3,381,005   55,035
10  2005               ZM de Minatitl�n    3   3,745,073   58,668
11  2010               ZM de Minatitl�n    3   4,106,054   63,018
12  1980            ZM de Coatzacoalcos    4   1,111,266    4,871
13  2000            ZM de Coatzacoalcos    4   2,269,995   56,619
14  2005            ZM de Coatzacoalcos    4   2,523,321   58,393
15  2010            ZM de Coatzacoalcos    4   2,728,790   61,301
16  1980                 ZM de Monterrey   5     568,004    1,309
17  2000                 ZM de Monterrey   5   1,540,452   29,928
18  2005                 ZM de Monterrey   5   1,710,766   32,456
19  2010                 ZM de Monterrey   5   1,936,126  352,083
20  1980  ZM de Colima-Villa de �lvarez    6     491,797    6,101
21  2000  ZM de Colima-Villa de �lvarez    6   1,352,035   22,380
22  2005  ZM de Colima-Villa de �lvarez    6   1,575,026   24,485
23  2010  ZM de Colima-Villa de �lvarez    6   1,751,430   26,672
24  1980           ZM de Puebla-Tlaxcala   7     732,845    2,502
25  2000           ZM de Puebla-Tlaxcala   7   1,269,179   12,327
26  2005           ZM de Puebla-Tlaxcala   7   1,425,210   14,999
27  2010           ZM de Puebla-Tlaxcala   7   1,609,504   17,031
28  1980        ZM de Monclova-Frontera    8     567,365    4,125
29  2000        ZM de Monclova-Frontera    8   1,218,817   19,661
30  2005        ZM de Monclova-Frontera    8   1,313,338   22,184
31  2010        ZM de Monclova-Frontera    8   1,332,131   25,828
32  1980                    ZM de Toluca   9     689,195    2,364
33  2000                    ZM de Toluca   9   1,007,291   14,904
34  2005                    ZM de Toluca   9   1,110,890   16,976
35  2010                    ZM de Toluca   9   1,215,817   18,993
36  1980                   ZM de Tijuana  10     323,275      782
37  2000                   ZM de Tijuana  10     816,481    9,231
38  2005                   ZM de Tijuana  10     950,828   11,075
39  2010                   ZM de Tijuana  10   1,097,025   12,612

In [13]:
panel.year.dtype

dtype('int64')

In [15]:
reg  = PanelOLS(y = panel['pop'], x = panel['area'],time_effects=True)

AttributeError: 'Series' object has no attribute 'items'

In [17]:
panel.year2 =  pd.to_datetime(panel.year, format='YYYY')

ValueError: time data 1980 does not match format 'YYYY' (match)